version: '3'
services:
  prixi:
    build: .
    ports:
      - "9001:9001"
    environment:
      - TARGET_URL=${TARGET_URL:-https://www.google.com}
      - LOCAL_PROTOCOL=${LOCAL_PROTOCOL:-http}
      - LOCAL_HOSTNAME=${LOCAL_HOSTNAME:-localhost}
      - LOCAL_PORT=${LOCAL_PORT:-9001}
      - PROXY_PORT=${PROXY_PORT:-9001}
    env_file:
      - .env
